/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignments;

public class App {

    // int x = (int) (Math.random() * 10) % 8;
    public static void main(String[] args) {
        // boolean alive = true;
        NumberInput NInput = new NumberInput();
        System.out.println("welcome to the game. Enter the pet favours");

        Cat cat = new Cat();

        while (cat.alive == true) {

            int option = NInput.getValidatedFeed(" Enter:[1 - feed][2 - water][3 - boredom][4 - parasites][0 - EXIT]");

            switch (option) {
                case 1:
                    // System.out.flush();
                    cat.feed();
                    cat.tick();
                    System.out.print("\033[H\033[2J");
                    cat.infoView();
                    cat.animate();
                    // break;
            }

            switch (option) {
                case 2:
                    cat.water();
                    cat.tick();
                    System.out.print("\033[H\033[2J");
                    cat.infoView();
                    cat.animate();
                    // break;
            }
            switch (option) {
                case 3:
                    cat.boredom();
                    cat.tick();
                    System.out.print("\033[H\033[2J");
                    cat.infoView();
                    cat.animate();
                    // break;
            }
            switch (option) {
                case 4:
                    cat.parasites();
                    cat.tick();
                    System.out.print("\033[H\033[2J");
                    cat.infoView();
                    cat.animate();
                    // break;
            }
            switch (option) {
                case 0:
                    cat.alive = false;

                    System.out.print("\033[H\033[2J");
                    cat.animate();

                    break;
            }
            if (cat.alive == false) {
                System.out.print("\033[H\033[2J");
                cat.infoView();
                cat.animate();
                System.out.println("GAME END");
                System.out.println("Thank you - Come again");

                break;
            }
        }

    }
}
